// FXnRXn copyright

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace Abyss_Tags
{
	// Input Tags
	UE_DECLARE_GAMEPLAY_TAG_EXTERN (InputTag_Move);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN (InputTag_Look);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN (InputTag_Fire);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN (InputTag_ADS);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN (InputTag_Reload);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN (InputTag_SwitchWeapon);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN (InputTag_Interact);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN (InputTag_Sprint);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN (InputTag_Slide);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN (InputTag_Grenade);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN (InputTag_Heal);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN (InputTag_Ability1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN (InputTag_Ability2);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN (InputTag_Ultimate);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN (InputTag_Pause);
	
	// Ability Tags
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Fire);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ADS);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Reload);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Sprint);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Slide);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Grenade);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Heal);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Melee);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Shockwave);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ElementalRounds);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Overdrive);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_SummonMinions);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_BossGroundSlam);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_BossCharge);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_BossRanged);
	
	
	// State Tags
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( State_Dead);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( State_Downed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( State_Invulnerable);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( State_Sprinting);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( State_Sliding);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( State_ADS);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( State_Firing);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( State_Reloading);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( State_Stunned);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( State_Frozen);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( State_Burning);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( State_Poisoned);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( State_Electrified);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( State_Overdrive);
	
	
	
	// Jump Tags
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( Ability_Jump);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( State_Jumping);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( State_InAir);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( Event_Movement_Jump);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( Event_Movement_Landed);

	// Crouch Tags
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( Ability_Crouch);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( State_Crouching);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( Event_Movement_Crouch);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN( GameplayCue_Movement_Crouch);
}

